### ISSUE TITLE
v4.0.0

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#151]
- [x] rename `exclusiveFormatMaximum` to `formatExclusiveMaximum` (in PR #150)
- [x] `useDeafults: 'clone'` should be the default
- [x] typescript type definitions (#148)
- [x] dependencies in allErrors mode (#73)
- [x] error parameters in v5 errors (to add messages to ajv-i18n)
- [x] rename `async` property of validation function to `$async` to avoid name clash with meteor

**Comment by epoberezkin** [comment]
released
